# Generated by Django 3.1 on 2021-11-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20211119_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Class',
            field=models.IntegerField(default=-2009),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='roll_no',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sports_game',
            name='Timing_in_hour',
            field=models.FloatField(),
        ),
    ]
