# Generated by Django 3.1 on 2021-11-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20211123_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Class',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
