# Generated by Django 3.1 on 2021-11-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_student_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_task',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student_task',
            name='task',
        ),
        migrations.AddField(
            model_name='student_task',
            name='Class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_task',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_task',
            name='sub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
