# Generated by Django 3.1 on 2021-11-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20211127_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_task',
            old_name='marks',
            new_name='o_marks',
        ),
        migrations.AddField(
            model_name='student_task',
            name='t_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
