# Generated by Django 3.1 on 2021-11-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_auto_20211128_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_task_assign',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='tasks/pdf/'),
        ),
    ]
