# Generated by Django 3.1 on 2021-11-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_student_task_assign_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_task_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('task_id', models.TextField(blank=True, null=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('result', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='student_task_assign',
            old_name='sub_date',
            new_name='submission_date',
        ),
        migrations.RenameField(
            model_name='student_task_assign',
            old_name='t_marks',
            new_name='total_marks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
