# Generated by Django 3.1 on 2021-11-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_auto_20211129_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_task_result',
            name='resultp',
            field=models.FileField(blank=True, null=True, upload_to='tasks/pdf/'),
        ),
        migrations.AlterField(
            model_name='student_task_result',
            name='task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
