# Generated by Django 3.1 on 2021-12-06 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_auto_20211204_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_task_assign',
            name='std_task',
        ),
        migrations.AddField(
            model_name='student_task_assign',
            name='Class',
            field=models.IntegerField(default=-2027),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_task_assign',
            name='Teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='S_task_a', to=settings.AUTH_USER_MODEL),
        ),
    ]
