# Generated by Django 3.1 on 2021-12-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_auto_20211206_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_task_assign',
            old_name='Teacher_id',
            new_name='Teacher',
        ),
    ]
