# Generated by Django 3.1 on 2021-12-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0018_auto_20211207_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_task_assign',
            old_name='Class',
            new_name='class_s',
        ),
        migrations.RenameField(
            model_name='student_task_assign',
            old_name='Teacher',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='teachers_class_lecture',
            old_name='Class',
            new_name='class_t',
        ),
        migrations.RenameField(
            model_name='teachers_class_lecture',
            old_name='End_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='teachers_class_lecture',
            old_name='Lecture',
            new_name='lecture',
        ),
        migrations.RenameField(
            model_name='teachers_class_lecture',
            old_name='Start_time',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='teachers_class_lecture',
            old_name='Teacher',
            new_name='teacher',
        ),
    ]
